spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.devtools.restart.enabled=false
spring.sql.init.mode=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.whitelabel.enabled=false
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
server.compression.enabled=true
